export const t_names = ()=>{
    const names = [
        "Checkmate Chronicles",
        "The Grand Gambit",
        "Kings & Queens",
        "Battle of the Board",
        "The Royal Clash",
        "64 Squares",
        "Crown & Check",
        "The Chess Dominion",
        "Knightfall",
        "The Final Gambit",
        "War of the Pieces",
        "The Checkmate Arena",
        "Crown Wars",
        "The Royal Rumble",
        "Board of Legends",
        "The Infinite Check",
        "Kings of the Board",
        "The Grandmaster's Trial",
        "Pawn to Glory",
        "The Last Move",
        "Checkmate Showdown",
        "The 64-Square Wars",
        "Rise of the Knights",
        "The Royal Gambit",
        "Empire of Chess",
        "The Tactical Battlefield",
        "Crowned in Check",
        "The Endgame",
        "Masters of the Board",
        "The Chess Conquest",
        "Knight's Dominion",
        "The Ultimate Gambit",
        "Checkmate Royale",
        "The King's Arena",
        "The Black & White War",
        "The Strategic Crown",
        "The Boardroom Battle",
        "The Chess Colosseum",
        "The Grand Chess War",
        "The Checkered Crown"
    ];
    return names[Math.floor(Math.random() * names.length)];
};

// -- INSERT INTO players (name, rating) VALUES
// -- ('Divyansh Agrawal',1500)
// -- ('Arjun Mehta', 2450),
// -- ('Vikram Sharma', 2385),
// -- ('Rahul Verma', 2310),
// -- ('Aditya Rao', 2265),
// -- ('Rohan Kapoor', 2190),
// -- ('Karan Malhotra', 2145),
// -- ('Aman Gupta', 2080),
// -- ('Siddharth Jain', 2025),
// -- ('Nikhil Agarwal', 1985),
// -- ('Varun Iyer', 1940),
// -- ('Yash Patel', 1895),
// -- ('Ankit Mishra', 1840),
// -- ('Pranav Joshi', 1795),
// -- ('Harsh Vardhan', 1750),
// -- ('Devansh Singh', 1710),
// -- ('Ayush Tiwari', 1665),
// -- ('Manav Bansal', 1620),
// -- ('Shrey Saxena', 1585),
// -- ('Dhruv Chawla', 1540),
// -- ('Kunal Arora', 1495),
// -- ('Aarav Nair', 1450),
// -- ('Ishaan Kulkarni', 1410),
// -- ('Kabir Deshmukh', 1365),
// -- ('Ritvik Soni', 1320),
// -- ('Ansh Srivastava', 1280),
// -- ('Mohit Yadav', 1245),
// -- ('Rishabh Pandey', 1190),
// -- ('Tanmay Dubey', 1140),
// -- ('Lakshya Bhatt', 1085),
// -- ('Samar Khan', 1020);
