export const t_names = ()=>{
    const names = [
        "Checkmate Chronicles",
        "The Grand Gambit",
        "Kings & Queens",
        "Battle of the Board",
        "The Royal Clash",
        "64 Squares",
        "Crown & Check",
        "The Chess Dominion",
        "Knightfall",
        "The Final Gambit",
        "War of the Pieces",
        "The Checkmate Arena",
        "Crown Wars",
        "The Royal Rumble",
        "Board of Legends",
        "The Infinite Check",
        "Kings of the Board",
        "The Grandmaster's Trial",
        "Pawn to Glory",
        "The Last Move",
        "Checkmate Showdown",
        "The 64-Square Wars",
        "Rise of the Knights",
        "The Royal Gambit",
        "Empire of Chess",
        "The Tactical Battlefield",
        "Crowned in Check",
        "The Endgame",
        "Masters of the Board",
        "The Chess Conquest",
        "Knight's Dominion",
        "The Ultimate Gambit",
        "Checkmate Royale",
        "The King's Arena",
        "The Black & White War",
        "The Strategic Crown",
        "The Boardroom Battle",
        "The Chess Colosseum",
        "The Grand Chess War",
        "The Checkered Crown"
    ];
    return names[Math.floor(Math.random() * names.length)];
};

export const team_names = ()=>{
    const names = [
        "The Pawn Stars",
        "Royal Forks",
        "Perpetual Checkers",
        "The Mating Net",
        "Castled Kings",
        "Bishop's Battalion",
        "The Center Squares",
        "Tempo Tyrants",
        "The Passed Pawns",
        "Checkmate Cartel",
        "Lord of the Kings",
        "Game of Pawns",
        "Queenside Scrappers",
        "Men in Black & White",
        "The Magic Squares",
        "Poisoned Pawns",
        "The Back Rank Brawlers",
        "Blunder Busters",
        "Diagonal Demons",
        "The Forking Knights",
        "Sicilian Mob",
        "The Pinning Punks",
        "Skewer Squad",
        "64 Square Syndicate",
        "Woodpushers Anonymous",
        "The Ruy Lopez Renegades",
        "E4 Elite",
        "Checkmate Chasers",
        "The Smothered Mates",
        "Time Trouble Terrors"
    ];
    return names[Math.floor(Math.random() * names.length)];
};

